name: Forecast Pull Request Action
author: Kvalifik
description: Automatically updates pull request titles and descriptions with Forecast project ticket information and links
branding:
  icon: link-2
  color: blue
inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
  forecast-project-id:
    description: Id for the Forecast project
    required: true
  ticket-regex:
    description: Regex to match Forecast ticket in branch name (default matches T123 or P123)
    default: ^[TP]\d+
    required: false
  ticket-regex-flags:
    description: Flags to add to ticket-regex
    default: i
    required: false
  exception-regex:
    description: Regex to allow exceptions where ticket-regex wouldn't match
    default: ^dependabot\/
    required: false
  exception-regex-flags:
    description: Flags to add to exception-regex
    required: false
  clean-title-regex:
    description: Regex used to delete text from PR title
    required: false
  clean-title-regex-flags:
    description: Flags to add to clean-title-regex
    required: false
runs:
  using: node20
  main: dist/index.js
